name: Build All Solvers

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build-windows:
    name: Build ESBMC with all Solvers (Windows)
    runs-on: windows-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: check python
      run: python --version
    - uses: actions/checkout@v1
    - name: Instal gnu tools (od)
      run: choco install -y gnuwin32-coreutils.portable
    - name: Check if od is on path
      run: od.exe --version
    - name: Check flail
      run: |
        python3.exe scripts/flail.py src/clang-c-frontend/headers/clang_stdint.hs out.c
        cat out.c    
    - name: Prepare Environment
      run: .\scripts\configure_environment.ps1
    - name: Install Boost
      run: choco install -y boost-msvc-14.1
    - name: Install Bison/Flex
      run: choco install -y winflexbison
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake.exe .. -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=C:\deps\clang\llvm9d -DClang_DIR=C:\deps\clang\llvm9d
    - name: Build ESBMC
      run: |
        cd build
        cmake --build .
